"""Calibrated average stored-tile byte sizes, per zoom, per tier.

GENERATED by ``backend/scripts/calibrate_tile_sizes.py`` against the bundled
``frontend/assets/tiles/uk.pmtiles`` (basemap) and ``uk-terrain.pmtiles``
(terrain) archives. Do not hand-edit — re-run the script and commit the
result if the bundled archives are ever regenerated.

Each table gives the average size in bytes of a *unique stored tile* at that
zoom (see the script's module docstring for why unique-tile averaging, not
addressed-tile averaging, is the sensible estimate for an arbitrary future
region extract). Missing zooms (no tiles present in the source archive at
that level) are omitted; callers should fall back to the nearest available
zoom or a small constant.

For reference only, the addressed-tile-weighted average (i.e. what you would
compute by dividing total tile-data bytes by every addressed tile id,
including deduplicated ocean runs) was also computed during calibration:
  basemap: z0=66726, z1=74702, z2=94652, z3=74966, z4=58444, z5=41530, z6=29101, z7=32901, z8=29602, z9=30024, z10=22221, z11=12767, z12=7250, z13=3692, z14=1772
  terrain: z0=121656, z1=111964, z2=138972, z3=105504, z4=102651, z5=89028, z6=55525, z7=56012, z8=54914, z9=43650, z10=31874, z11=22946, z12=27357
These are dominated by ocean dedup in our specific UK archive and are NOT
used — they would under-estimate a land-heavy or coastal-light selection.
"""

BASEMAP_AVG_TILE_BYTES: dict[int, int] = {
    0: 66726,
    1: 74702,
    2: 94652,
    3: 74966,
    4: 58444,
    5: 41530,
    6: 29101,
    7: 32901,
    8: 31077,
    9: 33700,
    10: 29416,
    11: 18558,
    12: 12668,
    13: 7644,
    14: 4099,
}

TERRAIN_AVG_TILE_BYTES: dict[int, int] = {
    0: 121656,
    1: 111964,
    2: 138972,
    3: 105504,
    4: 102651,
    5: 89028,
    6: 55525,
    7: 57657,
    8: 61844,
    9: 57935,
    10: 52740,
    11: 44547,
    12: 58579,
}
